version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: api
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    image: node:latest
    container_name: api
    restart: always
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: yarn start
